### ISSUE TITLE
bundle inilne into a single file or multiple files?

### ISSUE THREAD

**Issue by electriquo** [Krutsch/html-bundle#524]
mind me for asking. the documentation says
> The idea is to use HTML as Single File Component

does it mean that running html-bundle will bundle inline all js and css into a single html file, or will it output multiple bundled files?

**Comment by Krutsch** [comment]
Hey! It will bundle everything from the src path (default: "src"). 
If you have only one html file and everything is in there, the output should be a html file only. 

However, it is best practice to use this for critical things only and split and share CSS and JS if possible.

**Comment by Krutsch** [comment]
This is intended! 
The goal was not to have everything in one file (as output), I mean it depends on what your goal is but generally to be able to write JS within the HTML and let the bundler figure it out. You can use the critical flag for inlining some CSS.
